apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-release-v2
spec:
  selector:
    matchLabels:
      app: api-release
  replicas: 1
  template:
    metadata:
      labels:
        app: api-release
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: api-release
          image: quay.io/leandrop02/ex328-api-release:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080